name: Telegram Bot

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  send_message:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.8'  # Use Python 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install six
          pip install requests python-telegram-bot  # Install both requests and python-telegram-bot

      - name: Run the bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # GitHub secret for the bot token
        run: |
          python bot.py  # Run the bot script
